version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/npm-maven-extension

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Build framework
          command: ./mvnw clean install
      - run:
          name: Build sitedoc
          command: ./mvnw site site:stage
      - run:
          name: Build demo application
          command: |
            PROJECT_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
            cd demo
            ./mvnw clean install -s ../.circleci/settings.xml -Dnpm-maven-extension.version=$PROJECT_VERSION
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Import GPG key
          command: echo -e "$GPG_SECRET" | gpg --import --no-tty --batch --yes
      - run:
          name: Release artifact to Maven Central
          command: ./mvnw deploy -Prelease -s ./.circleci/settings.xml -Dgpg.passphrase=${GPG_PASSPHRASE}
      - run:
          name: Publish sitedoc
          command: ./mvnw scm-publish:publish-scm -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN}
          environment:
            GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
            GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
            GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
            GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.+/
            branches:
              only: /.+/
      - release:
          filters:
            tags:
              only: /.+/
            branches:
              ignore: /.*/
          requires:
            - build
