version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/npm-maven-extension

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Copy settings.xml
          command: mkdir -p ~/.m2 && cp ./.circleci/settings.xml ~/.m2/settings.xml
      - run:
          name: Build framework
          command: ./mvnw clean install
      - run:
          name: Build sitedoc
          command: ./mvnw site site:stage
      - run:
          name: Build demo application
          command: |
              cd demo
              ./mvnw clean install
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish sitedoc
          command: ./mvnw -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN} scm-publish:publish-scm
          environment:
            GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
            GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
            GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
            GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.+/
            branches:
              only: /.+/
      - release:
          filters:
            tags:
              only: /.+/
            branches:
              ignore: /.*/
          requires:
            - build
